apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dcasati/homelab
    targetRevision: HEAD
    path: infra/k8s-apps/mqtt-influx
  destination:
    server: https://kubernetes.default.svc
    namespace: iot-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s