apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-kiosk-nginx-config
  namespace: observability
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;

        # Only allow this exact path
        location = /d/cy7yjiENk/weather-station {
          proxy_pass http://kube-prom-stack-grafana.observability.svc.cluster.local:80;
        }

        # Redirect everything else
        location / {
          return 302 /d/cy7yjiENk/weather-station;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-kiosk-proxy
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-kiosk-proxy
  template:
    metadata:
      labels:
        app: grafana-kiosk-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: grafana-kiosk-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-kiosk-service
  namespace: observability
spec:
  selector:
    app: grafana-kiosk-proxy
  ports:
  - port: 80
    targetPort: 80
