apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
  namespace: tailscale
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://grafana-kiosk-service.observability.svc.cluster.local:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-kiosk-service
  namespace: tailscale
spec:
  selector:
    app: nginx-proxy
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-funnel
  namespace: tailscale
  annotations:
    tailscale.com/funnel: "true"
spec:
  rules:
  - host: "grafana-funnel"  # This will be used in the Tailscale URL
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-kiosk-service
            port:
              number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - "grafana-funnel"
