apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix-serve
  namespace: wikipedia-offline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwix-serve
  template:
    metadata:
      labels:
        app: kiwix-serve
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: fetch-zims
          image: alpine:3.20
          command:
            - /bin/sh
            - -ce
            - |
              set -eu
              if [ -z "$(ls -A /data 2>/dev/null || true)" ]; then
                echo "Empty /data, downloading ZIMs from /cfg/urls.txt"
                apk add --no-cache wget ca-certificates
                while read -r url; do
                  case "$url" in ""|\#*) continue ;; esac
                  fname="/data/$(basename "$url")"
                  [ -f "$fname" ] && { echo "Have $fname, skip"; continue; }
                  wget -O "$fname" "$url"
                done < /cfg/urls.txt
              else
                echo "/data not empty; skip download"
              fi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: zim-urls
              mountPath: /cfg
          securityContext:
            runAsUser: 0
      containers:
        - name: kiwix
          image: ghcr.io/kiwix/kiwix-serve:latest
          args: ["--port=8080", "/data"]
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 30
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits: { cpu: "2", memory: "2Gi" }
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: zim-data }
        - name: zim-urls
          configMap:
            name: zim-urls
            items: [{ key: urls.txt, path: urls.txt }]

