apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wikipedia-offline

resources:
  - ns.yaml
  - pvc.yaml
  - configmap.zim-urls.yaml
  - deployment.yaml
  - service.yaml
  - cronjob-refresh.yaml  # optional
