apiVersion: v1
kind: Service
metadata:
  name: kiwix-serve
  namespace: wikipedia-offline
spec:
  selector:
    app: kiwix-serve
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer

