apiVersion: v1
kind: ConfigMap
metadata:
  name: rss-weather-alert-script
  namespace: iot-stack
data:
  rss_weather_alert.py: |
    #!/usr/bin/env python3
    import feedparser, re, os, sys

    # get feed URL (env or CLI)
    FEED_URL = os.getenv("FEED_URL") or (sys.argv[1] if len(sys.argv) > 1 else None)
    AREA     = os.getenv("ALERT_AREA", "unknown")

    if not FEED_URL:
        print("Error: FEED_URL not set", file=sys.stderr)
        sys.exit(1)

    feed = feedparser.parse(FEED_URL)
    if feed.entries:
        entry   = feed.entries[0]
        title   = entry.title
        link    = entry.link
        summary = entry.get("summary","").strip()
    else:
        title, link, summary = "No alerts", "", ""

    def sanitize(text):
        return re.sub(r'[",]', '', text.replace("\n"," ")).strip()

    title   = sanitize(title)
    link    = sanitize(link)
    summary = sanitize(summary)

    # emit Influx line protocol
    print(f'rss_weather_alert,area={AREA} title="{title}",link="{link}",summary="{summary}"')
