apiVersion: batch/v1
kind: CronJob
metadata:
  name: rss-weather-alert
  namespace: iot-stack
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: alert-runner
            image: ghcr.io/dcasati/python-base:sha-11fec35
            command: ["python", "/app/rss_weather_alert.py"]
            env:
            - name: FEED_URL
              value: "https://weather.gc.ca/rss/battleboard/ab12_e.xml"
            - name: ALERT_AREA
              value: "ab12"
            - name: INFLUX_HOST
              value: "influxdb-service.iot-stack.svc"
            - name: INFLUX_PORT
              value: "8086"
            - name: INFLUX_DB
              value: "iot"
            - name: INFLUX_USER
              value: "admin"
            - name: INFLUX_PASSWORD
              value: "admin123"
            volumeMounts:
            - name: script-volume
              mountPath: /app/rss_weather_alert.py
              subPath: rss_weather_alert.py
          volumes:
          - name: script-volume
            configMap:
              name: rss-weather-alert-script
              defaultMode: 0o755
