apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://charts.gabe565.com
    chart: home-assistant
    targetRevision: 1.5.0
    helm:
      values: |
        controller:
          type: statefulset
          annotations:
            reloader.stakater.com/auto: "true"
          initContainers:
            hacs-installer:
              image: alpine:3.20
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  apk add --no-cache curl unzip
                  mkdir -p /config/custom_components
                  URL=$(curl -fsSL https://api.github.com/repos/hacs/integration/releases/latest \
                    | sed -n 's/.*"browser_download_url": *"\(.*zip\)".*/\1/p')
                  echo "Downloading $URL"
                  curl -fsSL "$URL" -o /tmp/hacs.zip
                  unzip -o /tmp/hacs.zip -d /config/custom_components
                  chown -R 1000:1000 /config/custom_components/hacs || true
              volumeMounts:
                - name: config
                  mountPath: /config
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: stable
        env:
          TZ: America/Edmonton
        persistence:
          config:
            enabled: true
            existingClaim: home-assistant-config
            mountPath: /config
        service:
          main:
            ports:
              http:
                port: 8123
        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: ha.dcasati.net
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - ha.dcasati.net
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          runAsNonRoot: true
  destination:
    server: https://kubernetes.default.svc
    namespace: iot-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
