apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt-discovery-bridge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/dcasati/homelab.git
    targetRevision: main
    path: infra/manifests/mqtt-discovery-bridge
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
