{
 "title": "Weather Station",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Weather Alerts",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT * FROM rss_weather_alert\nWHERE area = 'ab12'\nORDER BY time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT LAST(\"temperature\") FROM \"mqtt_consumer\"\n"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$device",
     "query": "SELECT mean(\"wind_dir_deg\") \nFROM \"mqtt_consumer\" \nWHERE $timeFilter and device = 'Acurite-5n1' \nGROUP BY time($__interval), \"device\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$device",
     "query": "SELECT mean(\"wind_avg_km_h\") \nFROM \"mqtt_consumer\" \nWHERE $timeFilter and device = 'Acurite-5n1' \nGROUP BY time($__interval), \"device\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$device",
     "query": "SELECT mean(\"humidity\") \nFROM \"mqtt_consumer\" \nWHERE $timeFilter and device = 'Acurite-5n1' \nGROUP BY time($__interval), \"device\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$device",
     "query": "SELECT (mean(\"temperature_F\") - 32) * 5 / 9 AS \"temperature_C\"\nFROM \"mqtt_consumer\"\nWHERE $timeFilter AND \"device\" = 'Acurite-5n1'\nGROUP BY time($__interval), \"device\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Daylight Hours ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$device",
     "query": "SELECT last(\"value\") FROM \"daylight_string\""
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$device",
     "query": "SELECT last(\"value\") FROM \"daylight_hours\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"forecast\") FROM \"forecast_summary\"\n"
    }
   ]
  },
  {
   "title": "Sunset",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$device",
     "query": "SELECT last(\"value\") FROM \"sunset\""
    }
   ]
  },
  {
   "title": "Sunrise",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$device",
     "query": "SELECT last(\"value\") FROM \"sunrise\""
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "$tag_device",
     "query": "SELECT mean(\"wind_avg_km_h\") \nFROM \"mqtt_consumer\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"device\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_device",
     "query": "SELECT (mean(\"temperature_F\") - 32) * 5 / 9 AS \"temperature_C\"\nFROM \"mqtt_consumer\"\nWHERE $timeFilter AND \"device\" = 'Acurite-5n1'\nGROUP BY time($__interval), \"device\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_device",
     "query": "SELECT mean(\"humidity\") \nFROM \"mqtt_consumer\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"device\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "alias": "$tag_device",
     "query": "SELECT mean(\"pressure\") \nFROM \"mqtt_consumer\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"device\" fill(null)\n"
    }
   ]
  }
 ]
}