apiVersion: batch/v1
kind: CronJob
metadata:
  name: forecast-job
  namespace: iot-stack
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: forecast
            image: ghcr.io/dcasati/forecasting:sha-abc123
            env:
            - name: INFLUX_HOST
              value: "influxdb.iot-stack.svc"
            - name: INFLUX_PORT
              value: "8086"
            - name: INFLUX_DB
              value: "iot"
          restartPolicy: OnFailure
