apiVersion: v1
items:
- apiVersion: v1
  data:
    MM_PLUGINSETTINGS_CLIENTDIRECTORY: Li9jbGllbnQvcGx1Z2lucw==
  kind: Secret
  metadata:
    annotations:
      meta.helm.sh/release-name: mattermost
      meta.helm.sh/release-namespace: mattermost
    creationTimestamp: "2026-02-28T21:24:37Z"
    labels:
      app.kubernetes.io/instance: mattermost
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mattermost-team-edition
      helm.sh/chart: mattermost-team-edition-6.6.93
    name: mattermost-mattermost-team-edition-config
    namespace: mattermost
    resourceVersion: "4985"
    uid: 7280f18f-10f7-46e0-9cb8-4dc4bdc40fb3
  type: Opaque
- apiVersion: v1
  data:
    mattermost.dbsecret: REDACTED
  kind: Secret
  metadata:
    annotations:
      meta.helm.sh/release-name: mattermost
      meta.helm.sh/release-namespace: mattermost
    creationTimestamp: "2026-02-28T21:24:37Z"
    labels:
      app.kubernetes.io/instance: mattermost
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mattermost-team-edition
      helm.sh/chart: mattermost-team-edition-6.6.93
    name: mattermost-mattermost-team-edition-mattermost-dbsecret
    namespace: mattermost
    resourceVersion: "4986"
    uid: e1bf4723-d098-4840-b022-bfbc37bd21e3
  type: Opaque
# Helm release secret (sh.helm.release.v1.mattermost.v1) removed - contains sensitive data
kind: List
metadata:
  resourceVersion: ""
