#cloud-config
hostname: "microk8s-main"
package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - net-tools
users:
  - default
  - name: dcasati
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINY8q+Ww2leih7SMZQqaM8a7CyCD1rI8EJ9oKeQbDjq9 dcasati@WIN-THINK24
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
    - apt update
    - apt install -y qemu-guest-agent net-tools
    - timedatectl set-timezone America/Edmonton
    - systemctl start qemu-guest-agent
    # microk8s
    - snap install microk8s --classic
    - microk8s status --wait-ready
    - microk8s enable metallb:172.16.5.240-172.16.5.245
    - microk8s enable dashboard
    - microk8s enable observability
    - mkdir -p /home/dcasati/.kube
    - microk8s config > /home/dcasati/.kube/config
    - chown -f -R dcasati /home/dcasati/.kube
    - usermod -a -G microk8s dcasati
    - snap alias microk8s.kubectl kubectl
    # argoCD
    - microk8s helm3 repo add argo https://argoproj.github.io/argo-helm
    - microk8s helm3 repo update
    - microk8s kubectl create namespace argocd
    - microk8s helm3 install argocd argo/argo-cd -n argocd
    - echo "done" > /tmp/cloud-config.done
