apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - influxdb/deployment.yaml
  - mosquitto/deployment.yaml
  - telegraf/deployment.yaml
  - forecasting/configmap.yaml
  - forecasting/cronjob.yaml
  - sunrise/configmap.yaml
  - sunrise/sunrise-cronjob.yaml
  - vesync/configmap.yaml
  - vesync/cronjob.yaml
  - vesync/secret.yaml

# Removed commonLabels to avoid immutable selector conflicts
# Individual resources should have their own appropriate labels

images:
  - name: ghcr.io/dcasati/python-base
    newTag: sha-644c3a4
