name: Build and Push Base Image

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'infra/k8s-apps/base-images/**'
      - '.github/workflows/build-images.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/k8s-apps/base-images/**'
      - '.github/workflows/build-images.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dcasati/python-base

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=sha-{{sha}}
          type=ref,event=branch
          type=ref,event=pr

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./infra/k8s-apps/base-images
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update kustomization with new image
      run: |
        echo "Updating kustomization.yaml with new image tag..."
        cd infra
        ./update-images.sh ${{ github.sha }}
        
    - name: Commit and push kustomization updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected, committing..."
          git add infra/k8s-apps/iot-stack/kustomization.yaml
          git commit -m "Auto-update python-base image to sha-${{ github.sha }}"
          git push
          echo "Kustomization updated and pushed automatically"
        else
          echo "No changes to commit"
        fi

    - name: Output completion details
      run: |
        echo "Build and deployment update completed!"
        echo ""
        echo "Built and pushed images:"
        echo "${{ steps.meta.outputs.tags }}"
        echo ""
        echo "Primary tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}"
        echo ""
        echo "Kustomization.yaml automatically updated"
        echo "ArgoCD will sync the new image automatically"
