name: Build and Push Container Images

on:
  push:
    branches:
      - main
    paths:
      - 'infra/k8s-apps/**/Dockerfile'
      - 'infra/k8s-apps/**/*.py'
      - 'infra/k8s-apps/**/requirements.txt'
  pull_request:
    paths:
      - 'infra/k8s-apps/**/Dockerfile'
      - 'infra/k8s-apps/**/*.py'
      - 'infra/k8s-apps/**/requirements.txt'

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      forecasting: ${{ steps.changes.outputs.forecasting }}
      sunrise: ${{ steps.changes.outputs.sunrise }}
      base-images: ${{ steps.changes.outputs.base-images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            forecasting:
              - 'infra/k8s-apps/iot-stack/forecasting/**'
            sunrise:
              - 'infra/k8s-apps/iot-stack/sunrise/**'
            base-images:
              - 'infra/k8s-apps/base-images/**'

  build-forecasting:
    needs: detect-changes
    if: needs.detect-changes.outputs.forecasting == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/dcasati/forecasting
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=sha-{{sha}},enable=true
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./infra/k8s-apps/iot-stack/forecasting
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-sunrise:
    needs: detect-changes
    if: needs.detect-changes.outputs.sunrise == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/dcasati/sunrise
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=sha-{{sha}},enable=true
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./infra/k8s-apps/iot-stack/sunrise
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-base-images:
    needs: detect-changes
    if: needs.detect-changes.outputs.base-images == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/dcasati/homelab-base
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=sha-{{sha}},enable=true
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./infra/k8s-apps/base-images
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
